FROM mysql:8.0

# Set environment variables
ENV MYSQL_ROOT_PASSWORD=Root@123
ENV MYSQL_DATABASE=form_app

# Copy initialization script
COPY init.sql /docker-entrypoint-initdb.d/

# Expose MySQL port
EXPOSE 3306 