FROM mysql:8.0.33-debian


# Use the default mysql user
USER mysql

# Copy the initialization script to the entrypoint directory
COPY init.sql /docker-entrypoint-initdb.d/

# Expose MySQL port
EXPOSE 3306




#custom-mysql   latest    e6e011999c29   About an hour ago   772MB

#custom-mysql   v1        2cc0c9b7af1d   About an hour ago   610MB
#Reduced by 160mb - used dedian